const lists = [
  [ ["empty_jar", "debatable_pos_left", "Is the jar on the left empty?"], 
    ["open_box", "debatable_neg_right", "Isn't the box on the right open?"], 
    ["striped_sock", "clearly_pos_right", "Is the sock on the right striped?"], 
    ["blue_towel", "clearly_pos_left", "Is the towel on the left blue?"], 
    ["full_cup", "debatable_neg_left", "Isn't the cup on the left full?"], 
    ["round_plate", "clearly_neg_right", "Isn't the plate on the right round?"], 
    ["straight_line", "debatable_pos_right", "Is the line on the right straight?"], 
    ["yellow_folder", "clearly_neg_left", "Isn't the folder on the left yellow?"] ], // List 1
  [ ["open_box", "debatable_pos_right", "Is the box on the right open?"], 
    ["empty_jar", "clearly_neg_left", "Isn't the jar on the left empty?"], 
    ["straight_line", "clearly_neg_right", "Isn't the line on the right straight?"], 
    ["blue_towel", "debatable_neg_right", "Isn't the towel on the right blue?"], 
    ["full_cup", "debatable_pos_left", "Is the cup on the left full?"], 
    ["striped_sock", "debatable_neg_left", "Isn't the sock on the left striped?"], 
    ["round_plate", "clearly_pos_right", "Is the plate on the right round?"], 
    ["yellow_folder", "clearly_pos_left", "Is the folder on the left yellow?"] ], // List 2
  [ ["round_plate", "debatable_neg_left", "Isn't the plate on the left round?"], 
    ["yellow_folder", "debatable_neg_right", "Isn't the folder on the right yellow?"], 
    ["empty_jar", "clearly_pos_left", "Is the jar on the left empty?"], 
    ["striped_sock", "debatable_pos_left", "Is the sock on the left striped?"], 
    ["open_box", "clearly_neg_right", "Isn't the box on the right open?"], 
    ["blue_towel", "debatable_pos_right", "Is the towel on the right blue?"], 
    ["full_cup", "clearly_neg_left", "Isn't the cup on the left full?"], 
    ["straight_line", "clearly_pos_right", "Is the line on the right straight?"] ], // List 3
  [ ["yellow_folder", "debatable_pos_right", "Is the folder on the right yellow?"], 
    ["straight_line", "debatable_neg_left", "Isn't the line on the left straight?"], 
    ["full_cup", "clearly_pos_left", "Is the cup on the left full?"], 
    ["round_plate", "debatable_pos_left", "Is the plate on the left round?"], 
    ["blue_towel", "clearly_neg_right", "Isn't the towel on the right blue?"], 
    ["striped_sock", "clearly_neg_left", "Isn't the sock on the left striped?"], 
    ["empty_jar", "debatable_neg_right", "Isn't the jar on the right empty?"], 
    ["open_box", "clearly_pos_right", "Is the box on the right open?"] ], // List 4
  [ ["empty_jar", "debatable_pos_right", "Is the jar on the right empty?"], 
    ["straight_line", "debatable_pos_left", "Is the line on the left straight?"], 
    ["yellow_folder", "clearly_neg_right", "Isn't the folder on the right yellow?"], 
    ["open_box", "debatable_neg_left", "Isn't the box on the left open?"], 
    ["striped_sock", "clearly_pos_left", "Is the sock on the left striped?"], 
    ["full_cup", "debatable_neg_right", "Isn't the cup on the right full?"], 
    ["blue_towel", "clearly_pos_right", "Is the towel on the right blue?"], 
    ["round_plate", "clearly_neg_left", "Isn't the plate on the left round?"] ], // List 5
  [ ["blue_towel", "debatable_neg_left", "Isn't the towel on the left blue?"], 
    ["full_cup", "debatable_pos_right", "Is the cup on the right full?"], 
    ["straight_line", "clearly_neg_left", "Isn't the line on the left straight?"], 
    ["striped_sock", "debatable_neg_right", "Isn't the sock on the right striped?"], 
    ["open_box", "debatable_pos_left", "Is the box on the left open?"], 
    ["empty_jar", "clearly_neg_right", "Isn't the jar on the right empty?"], 
    ["yellow_folder", "clearly_pos_right", "Is the folder on the right yellow?"], 
    ["round_plate", "clearly_pos_left", "Is the plate on the left round?"] ], // List 6
  [ ["straight_line", "clearly_pos_left", "Is the line on the left straight?"], 
    ["yellow_folder", "debatable_neg_left", "Isn't the folder on the left yellow?"], 
    ["striped_sock", "debatable_pos_right", "Is the sock on the right striped?"], 
    ["full_cup", "clearly_neg_right", "Isn't the cup on the right full?"], 
    ["open_box", "clearly_neg_left", "Isn't the box on the left open?"], 
    ["blue_towel", "debatable_pos_left", "Is the towel on the left blue?"], 
    ["round_plate", "debatable_neg_right", "Isn't the plate on the right round?"], 
    ["empty_jar", "clearly_pos_right", "Is the jar on the right empty?"] ], // List 7
  [ ["blue_towel", "clearly_neg_left", "Isn't the towel on the left blue?"], 
    ["empty_jar", "debatable_neg_left", "Isn't the jar on the left empty?"], 
    ["round_plate", "debatable_pos_right", "Is the plate on the right round?"], 
    ["open_box", "clearly_pos_left", "Is the box on the left open?"], 
    ["straight_line", "debatable_neg_right", "Isn't the line on the right straight?"], 
    ["full_cup", "clearly_pos_right", "Is the cup on the right full?"], 
    ["yellow_folder", "debatable_pos_left", "Is the folder on the left yellow?"], 
    ["striped_sock", "clearly_neg_right", "Isn't the sock on the right striped?"] ], // List 8
];